[package]
name = "hello-noise"
version = "0.1.0"
edition = "2024"

[dependencies]
egui = "0.33.3"
egui-wgpu = "0.33.3"
eframe = { version = "0.33.3", features = ["wgpu"] }
env_logger = "0.11.5"
enum-iterator = "2.3.0"
